name: Deploy to Hetzner Load Balancer Targets

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Ensure this runner has network access to the private instances

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Consider using an access token

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER_NAME }}:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER_NAME }}:latest

        
      - name: Get Hetzner Servers
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.HETZNER_API_TOKEN }}" "https://api.hetzner.cloud/v1/servers")
          SERVERS=$(echo "$RESPONSE" | jq -r --arg cname "${{ secrets.DOCKER_CONTAINER_NAME }}" '.servers[] | select(.name | contains($cname + "-")) | .private_net[0].ip' | paste -sd ' ' -)
          echo "servers=$SERVERS" >> $GITHUB_ENV
          SERVER_NAMES=$(echo "$RESPONSE" | jq -r --arg cname "${{ secrets.DOCKER_CONTAINER_NAME }}" '.servers[] | select(.name | contains($cname + "-")) | .name' | paste -sd ', ' -)
          echo "Selected Servers: $SERVER_NAMES"
        
      - name: Debug Servers Variable
        run: |
          echo "Servers: $SERVERS"
        
      - name: Add Bastion Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts
        
      - name: Deploy to Servers
        if: env.servers != ''
        run: |
          for TARGET_IP in $SERVERS; do
            echo "Deploying to $TARGET_IP"
            ssh -J root@${{ secrets.BASTION_IP }} root@$TARGET_IP <<EOF
              # Docker commands
              docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_CONTAINER_NAME}}:latest
              docker stop ${{secrets.DOCKER_CONTAINER_NAME}} || true
              docker rm ${{secrets.DOCKER_CONTAINER_NAME}} || true
              docker run -d --name ${{secrets.DOCKER_CONTAINER_NAME}} ${DOCKER_USERNAME}/${{secrets.DOCKER_CONTAINER_NAME}}:latest
          EOF
          done